In [ ]:
import pandas as pd
import fsspec
from zipfile import ZipFile
from io import BytesIO

def load_specific_csv_from_zip(url, filename):
    """Load one specific CSV from multi-file ZIP"""
    with fsspec.open(url, 'rb') as f:
        with ZipFile(BytesIO(f.read())) as z:
            return pd.read_csv(z.open(filename))

url = "gs://agntworks-data-dev/wheelsup/raw/wingx/WingX_2026.zip"
booked_flights = load_specific_csv_from_zip(url, 'AgntWorks/booked_flights.csv')

In [1]:
import pandas as pd
df=pd.read_parquet("gs://agntworks-data-dev/wheelsup/processed/wingx/lj_smid_us_revenue_clean_24_25_metro.parquet")
df.head(0)

Empty DataFrame
Columns: [FlightDate_utc, Operator, FromAirport, FromState, ToAirport, ToState, Hours, aircraft_tailsign, aircraft_model, aircraft_segment, fuel_uplift_usg, FlightDate_ET, year, month, dow, hour, FromMetro, ToMetro]
Index: []

In [3]:
import pandas as pd
df=pd.read_csv("gs://agntworks-data-dev/wheelsup/processed/transformed_icao_metro.csv")
df.head(1)

   icao    metro
0  GE30  Atlanta

In [5]:
import pandas as pd
df=pd.read_parquet("gs://agntworks-data-dev/wheelsup/processed/df_bookings_metros_final_merge.parquet")
print(df.head(0))

Empty DataFrame
Columns: [flightId, atlasreservationid, flightStatus, legOrder, flightoriginAirportId, flightoriginAirport, flightoriginAirportName, flightoriginAirportCity, flightoriginAirportState, flightoriginAirportCountry, flightdestinationAirportId, flightdestinationAirport, flightdestinationAirportName, flightdestinationAirportCity, flightdestinationAirportState, flightdestinationAirportCountry, flightEstimatedDepartureTime, flightEstimatedArrivalTime, flightEstimatedFlightHours, flightEstimatedBilledHours, flightActualDepartureTime, flightActualArrivalTime, flightActualFlightHours, flightActualBilledHours, flightrequestedAircraftType, flightrequestedAircraftCabinId, flightrequestedAircraftCabinName, flightrequestedAircraftTypeId, flightrequestedAircraftTypeName, flighttailNumber, flightactualAircraftCabinId, flightactualAircraftCabinName, flightactualAircraftId, flightactualAircraftTypeName, operatorName, operatorType, flightcost, reservationId, reservationStatus, reservationCreateDate, bookerMemberId, bookerContactId, passengerId, from_metro, to_metro, corridor, DOW, TOD, flightoriginAirportRegion, flightdestinationAirportRegion, flightEstimatedDepartureTime_ET, final_adjustment_pct]
Index: []

[0 rows x 52 columns]