In [12]:
import pandas as pd

In [13]:
icao_metro_pairing= pd.read_csv('gs://agntworks-data-dev/wheelsup/raw/icao_metro_pairing.csv')

In [14]:
icao_metro_pairing.head()

,Atlanta,North Florida,South Florida,Dallas,St. Louis,Minneapolis,Denver,Philadelphia,Nashville,Detroit,...,Bay Area,Boston,Phoenix Valley,Seattle,DMV,New York City,Charlotte,Houston,LA Basin,San Antonio
0,GE30,KBQK,PR20,41OK,70OK,SD87,SD04,23JY,AR72,OI91,...,DAF,LL59,KSGU,KSUN,41PA,6PS8,2VA0,20LA,KF70,NM83
1,2GE1,GE24,PR23,42OK,8OK8,SD57,KIEN,8PA0,KFCY,7OA7,...,U91,VT14,UT52,KTWF,72PN,N30,VA68,70LA,CA97,KHOB
2,69FD,5FA2,PR33,50OK,KMIO,KPIR,KPHP,PN44,70AR,OH77,...,3U0,VT80,UT28,MT40,51PA,7PA3,VA85,LA50,3CN2,NM95
3,KEGI,FD53,PR10,77OK,88NE,KICR,SD07,26PN,63AR,KILN,...,5OR0,33VT,03UT,93MT,PS02,44PN,VA72,1LA3,KSNA,KCNM
4,0FD5,89FD,PR06,99OK,NE57,SD03,SD72,7PN3,7AR7,9OI4,...,84OR,28VT,KMLF,53U,34PN,3PS7,KMTV,LS66,CL58,62NM

In [15]:
icao_metro_pairing.columns

Index(['Atlanta', 'North Florida', 'South Florida', 'Dallas', 'St. Louis',
       'Minneapolis', 'Denver', 'Philadelphia', 'Nashville', 'Detroit',
       'Pittsburgh', 'Chicago', 'Bay Area', 'Boston', 'Phoenix Valley',
       'Seattle', 'DMV', 'New York City', 'Charlotte', 'Houston', 'LA Basin',
       'San Antonio'],
      dtype='object')

In [16]:
icao_metro_transformation_report = pd.read_csv('gs://agntworks-data-dev/wheelsup/processed/icao_metro_transformation_report_20260425.csv')

In [17]:
icao_metro_transformation_report.head()

           metro  source_count  transformed_count  match
0        Atlanta           700                700   True
1  North Florida           539                539   True
2  South Florida           306                306   True
3         Dallas          1206               1206   True
4      St. Louis          1052               1052   True

In [18]:
transformed_icao_metro = pd.read_csv('gs://agntworks-data-dev/wheelsup/processed/transformed_icao_metro.csv')

In [19]:
transformed_icao_metro.head()

   icao    metro
0  GE30  Atlanta
1  2GE1  Atlanta
2  69FD  Atlanta
3  KEGI  Atlanta
4  0FD5  Atlanta

In [20]:
df_bookings_metros = pd.read_parquet("gs://agntworks-data-dev/wheelsup/processed/df_bookings_metros.parquet")

In [25]:
df_bookings_metros[df_bookings_metros['flightactualAircraftCabinName'] == 'Light']

,flightId,atlasreservationid,flightStatus,legOrder,flightoriginAirportId,flightoriginAirport,flightoriginAirportName,flightoriginAirportCity,flightoriginAirportState,flightoriginAirportCountry,...,flightcost,reservationId,reservationStatus,reservationCreateDate,bookerMemberId,bookerContactId,passengerId,from_metro,to_metro,corridor
0,1208327,794518,Cancelled,1,810,KTEB,Teterboro,Teterboro,NJ,US,...,0.00,794518,Quote,2024-04-01T06:06:30.000Z,17449,251218.0,251218.0,New York City,South Florida,New York City - South Florida
14,1208371,794548,Flown,1,160,KBNA,Nashville International,Nashville,TN,US,...,15840.00,794548,Pending,2024-04-01T12:13:45.000Z,10100,138896.0,138906.0,Nashville,South Florida,Nashville - South Florida
15,1208372,794548,Flown,2,1026,KBCT,Boca Raton,Boca Raton,FL,US,...,16560.00,794548,Pending,2024-04-01T12:13:45.000Z,10100,138896.0,138906.0,South Florida,Nashville,South Florida - Nashville
17,1208381,794555,Flown,2,815,KJKA,Gulf Shores International Jack Edwards Field,Gulf Shores,AL,US,...,11016.00,794555,Quote,2024-04-01T12:44:56.000Z,146114,813320.0,984656.0,Atlanta,Dallas,Atlanta - Dallas
18,1208387,794560,Flown,1,210,KCMH,John Glenn International,Columbus,OH,US,...,9720.00,794560,Quote,2024-04-01T13:55:10.000Z,2447,30626.0,30631.0,Pittsburgh,North Florida,Pittsburgh - North Florida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258264,1290266,847514,Booked,1,528,KEUG,Mahlon Sweet Field,Eugene,OR,US,...,9839.92,847514,Quote,2026-03-31T14:37:31.000Z,209072,975572.0,977045.0,Seattle,Denver,Seattle - Denver
258289,1285626,844549,Flown,2,2983,KHXD,Hilton Head,Hilton Head Island,SC,US,...,14018.50,844549,Quote,2026-02-12T07:05:27.000Z,13521,182211.0,182211.0,North Florida,Detroit,North Florida - Detroit
258298,1283857,843435,Booked,1,1012,KACK,Nantucket Memorial,Nantucket,MA,US,...,9912.00,843435,Quote,2026-01-24T16:51:36.000Z,4127,48032.0,48032.0,Boston,DMV,Boston - DMV
258306,1291778,845924,Booked,3,534,KTLH,Tallahassee International,Tallahassee,FL,US,...,9114.00,845924,Quote,2026-03-06T20:42:12.000Z,199142,947885.0,1284043.0,North Florida,North Florida,North Florida - North Florida
258321,1290266,847514,Booked,1,528,KEUG,Mahlon Sweet Field,Eugene,OR,US,...,9839.92,847514,Quote,2026-03-31T14:37:31.000Z,209072,975572.0,977060.0,Seattle,Denver,Seattle - Denver

In [22]:
# df_bookings_metros.to_excel(
#     "df_bookings_metros.xlsx",
#     index=False,
#     engine="xlsxwriter"
# )